language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
script: bundle exec rspec && bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: de9164829e91818d341aabb218c70ebcbb9ebc0e936b782013021e13a9a0b6b9
